export const lista = [
    //fekete
    {szimbolumkod: "&#9820;", nev: "bástya"},
    {szimbolumkod: "&#9822;", nev: "ló"},
    {szimbolumkod: "&#9821;", nev: "futó"},
    {szimbolumkod: "&#9819;", nev: "Királynő"},
    {szimbolumkod: "&#9818;", nev: "király"},
    {szimbolumkod: "&#9821;", nev: "futó"},
    {szimbolumkod: "&#9822;", nev: "ló"},
    {szimbolumkod: "&#9820;", nev: "bástya"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "&#9823;", nev: "paraszt"},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "", nev: ""},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9817;", nev: "paraszt"},
    {szimbolumkod: "&#9814;", nev: "bástya"},
    {szimbolumkod: "&#9816;", nev: "ló"},
    {szimbolumkod: "&#9815;", nev: "futó"},
    {szimbolumkod: "&#9813;", nev: "Királynő"},
    {szimbolumkod: "&#9812;", nev: "király"},
    {szimbolumkod: "&#9815;", nev: "futó"},
    {szimbolumkod: "&#9816;", nev: "ló"},
    {szimbolumkod: "&#9814;", nev: "bástya"},
]
export const kulcslista={
    szimbolumkód:"szimbolumkód",
    név:"név",
};